### ISSUE TITLE
Priority issues

### ISSUE THREAD

**Issue by NicoLaval** [sdmx-twg/vtl#518]
- [ ] [390](https://github.com/sdmx-twg/vtl/issues/390) - Review grammar to make UDOs more flexible
- [ ] [405](https://github.com/sdmx-twg/vtl/issues/405) - Grammar not acceptig valueDomainvalues starting with "_"
- [ ] [410](https://github.com/sdmx-twg/vtl/issues/410) - Cannot provide a set as input parameter for UDO
- [ ] [515](https://github.com/sdmx-twg/vtl/issues/515) - Keep/Drop wildcard
- [ ] [516](https://github.com/sdmx-twg/vtl/issues/516) - Add distance operators
- [ ] [Random](https://github.com/VTL-Community/VTL-Community/issues/56#issuecomment-2443465659)
- [ ] [517](https://github.com/sdmx-twg/vtl/issues/517) - year & month functions

**Comment by linardian** [comment]
I think we disussed enough in last workshop. I am closing the issue.
